### ISSUE TITLE
Update rules files

### ISSUE THREAD

**Issue by andrewhowdencom** [juju4/ansible-falco#2]
The rule files seem like they're reasonably out of date.

Perhaps it's better to use `lineinfile` to modify specific configuration blocks, so upstream can be used? Can then just control `falco_rules.local.yaml` with Ansible, and defer management of the rest of the package manager on the machine (which will keep them up to date)

**Comment by juju4** [comment]
I used to customize rules file as it was unique at the beginning.
didn't track upstream changes so closed I want in the last months but I started to move stuff to local file. My problem was some specific container usage required me customizing upstream rules, that's why you have two falco_rules in my template: one which is nearly upstream and another more modified.

I synced files with upstream

**Comment by andrewhowdencom** [comment]
<3 I'll close this issue as resolved. Thaanks!
